package main.core;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;

import javax.swing.JOptionPane;


public class LeaderBoard implements Serializable {


	private static final long serialVersionUID = 7487390213792955281L;
	private ArrayList<Score> scores;


	public LeaderBoard() {
		
		ObjectInputStream input;
		try {
			input = new ObjectInputStream(new FileInputStream("res/scores.ser"));
			scores = (ArrayList<Score>) input.readObject();
		} catch (IOException e) { 
			scores = new ArrayList<Score>(10);
		} catch (ClassNotFoundException e) {
			System.err.println("Classes do not match.  You are not using a file generated by this program");
			System.exit(1);
		}		
	}
	
	
	public void add(int time, int rows, int columns, int mines, String name) {
		
		Score score = new Score(rows, columns, mines, time, name);
		
		if (scores.size() == 0)
			scores.add(score);
		else {
			int index = 0;
			for (int i = 0; i < scores.size(); i++) {
				index = i;
				if (scores.get(i).compareTo(score) > 0) {
					if (i == scores.size() - 1) 
						index++;
					continue; 
				}
				else 
					break;
			}
			if (index < 10)
				scores.add(index, score);
		}
		

		try {
			ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream("res/scores.ser"));
			output.writeObject(scores);
			output.close();
		} catch (IOException e) {
			System.err.println("Error opening/writing to file, may not have write permission in current directory");
			e.printStackTrace(); // so you can see what went wrong
			System.exit(1);
		}
	}
	

	public void display() {
		
		if (scores.size() > 0) {
			String output = "";
			for (int i = 0; i < scores.size(); i++) 
				output += (i + 1) + ") " + scores.get(i).toString() + "\n";
			JOptionPane.showMessageDialog(null, output);
		}
		else 
			JOptionPane.showMessageDialog(null, "There are no scores to display");
	}
}